baseURL = 'http://flexagoon.com'
title = 'flexagoon.'
theme = 'hugo-coder'
languageCode = 'en'

enableEmoji = true

[params]
  author = 'flexagoon.'
  info = "world's first programming tomato"
  avatarurl = 'images/pfp.png'
  colorscheme = 'dark'
  since = 2022

  description = "flexagoon's website"
  keywords = 'blog,personal,developer,flexagoon,dart'

  customscss = ['scss/custom.scss']

[[params.social]]
  name = 'GitHub'
  icon = 'fa fa-github fa-2x'
  url = 'https://github.com/flexagoon'
  weight = 1
[[params.social]]
  name = 'Telegram'
  icon = 'fa fa-telegram fa-2x'
  url = 'https://t.me/flexagoon'
  weight = 2
[[params.social]]
  name = 'Reddit'
  icon = 'fa fa-reddit fa-2x'
  url = 'https://reddit.com/u/sevenisnotanumber2'
  weight = 3
[[params.social]]
  name = 'YouTube'
  icon = 'fa fa-youtube-play fa-2x'
  url = 'https://youtube.com/channel/UCT_zuaWs6SitJF2lvuHO7xw'
  weight = 4
[[params.social]]
  name = 'Email'
  icon = 'fa fa-envelope fa-2x'
  url = 'mailto:contact@flexagoon.com'
  weight = 5

# [[menu.main]]
#   name = 'Brand Guidelines'
#   url = 'brand/'
#   weight = 1
